application: booksengine
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /media/js
  static_dir: media/js

- url: /media/css
  static_dir: media/css

- url: /media/images
  static_dir: media/images

- url: .*
  script: main.py

