import logging
#make sure touchengine is on your path
#I'm lazy, I usually ln -s the touchengine directory into the root of the project :P
from touchengine import touchengineutil
from google.appengine.ext import db

#these are now generated by mogenerate.sh.  The only thing we have to figure out
#is how to keep from having to manually edit the a owner = db.UserProperty() line.
from BookShelf import BookShelf
from Book import Book

touchengineutil.decorateModuleNamed(__name__)
logging.info('Models in %r decorated', __name__)

# These were the handmade models for reference.
# 
# class BookShelf(db.Model):
#     """Metadata about User's Bookshelf"""
# 
#     name = db.StringProperty()
#     # rating_average = db.FloatProperty(default=0.0)
#     owner = db.UserProperty()
#     comment = db.StringProperty()
#     
# class Book(db.Model):
#     """A single instance of books"""
#     
#     date = db.DateTimeProperty(auto_now_add=True)
#     author = db.StringProperty()
#     copyright = db.DateTimeProperty()
#     title = db.StringProperty()
#     bookshelf = db.ReferenceProperty(BookShelf,
#                                  required=False,
#                                  collection_name='book_set')

