application: doctorpagers
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /rest/.*
  script: intgutil.py
- url: .*
  script: main.py
